const hasAnyEnv = (names = []) => names.some((name) => Boolean(process.env[name]));
const hasAllEnv = (names = []) => names.every((name) => Boolean(process.env[name]));

export const VIBECUT_PRESETS = [
    { id: 'cinematic', label: 'cinematic', prompt: 'cinematic background music for a polished social video, focused mood, clean edit points' },
    { id: 'trailer-epic', label: 'trailer / epic', prompt: 'epic trailer music with cinematic drums, rising tension, bold impacts, no vocals' },
    { id: 'action-trailer', label: 'action trailer', prompt: 'fast action trailer cue, punchy percussion, risers, impacts, energetic cuts' },
    { id: 'corporate-brand', label: 'corporate / brand', prompt: 'modern optimistic brand music, confident corporate pulse, clean synths and light percussion' },
    { id: 'fashion-club', label: 'fashion / club', prompt: 'stylish fashion show club track, glossy electronic groove, premium nightlife energy' },
    { id: 'short-commercial', label: 'short commercial', prompt: 'short commercial bed for social ad, upbeat hook, quick intro and clean ending' },
    { id: 'electronic', label: 'electronic', prompt: 'electronic social video music, tight drums, modern synth bass, polished mix' },
    { id: 'house', label: 'house', prompt: 'house music loop for reels, steady four-on-the-floor, warm chords, clean drop' },
    { id: 'hip-hop', label: 'hip hop', prompt: 'hip hop beat for short-form video, punchy drums, bass groove, instrumental' },
    { id: 'jazz', label: 'jazz', prompt: 'modern jazz background, tasteful chords, brushed drums, social video underscore' },
    { id: 'funk', label: 'funk', prompt: 'funk groove with tight bass, guitar chops, energetic social edit rhythm' },
    { id: 'rock', label: 'rock', prompt: 'driving rock instrumental for video montage, energetic drums and guitars' },
    { id: 'lofi', label: 'lofi', prompt: 'lofi beat for calm social video, warm texture, relaxed groove, instrumental' },
    { id: 'ambient-lounge', label: 'ambient / lounge', prompt: 'ambient lounge bed, smooth texture, subtle pulse, elegant background music' },
    { id: 'impact-whoosh', label: 'impact / whoosh', prompt: 'short impact and whoosh transition sound design for social video edit' },
    { id: 'riser-transition', label: 'riser / transition', prompt: 'short riser transition with clean sweep and ending impact' },
    { id: 'intro-opener', label: 'intro / opener', prompt: 'short opener sting, premium intro cue, clean logo reveal energy' },
    { id: 'podcast-talk-bed', label: 'podcast / talk bed', prompt: 'low-distraction podcast talk bed, subtle rhythm, warm background, no vocals' },
    { id: 'luxury-premium', label: 'luxury / premium', prompt: 'luxury premium brand music, minimal elegant groove, refined cinematic tone' },
    { id: 'tech-futuristic', label: 'tech / futuristic', prompt: 'futuristic tech product music, precise synth pulses, clean modern sound' },
    { id: 'emotional-inspiring', label: 'emotional / inspiring', prompt: 'emotional inspiring soundtrack, hopeful progression, cinematic but restrained' },
];

const elevenLabsFilters = [
    { id: 'prompt', label: 'Prompt', kind: 'prompt', source: 'native' },
    { id: 'music_length_ms', label: 'Duration', kind: 'duration', source: 'native', min: 3, max: 600 },
    { id: 'force_instrumental', label: 'Instrumental', kind: 'boolean', source: 'native' },
    { id: 'composition_plan', label: 'Composition plan', kind: 'structured', source: 'native', ui: 'future' },
    { id: 'sign_with_c2pa', label: 'C2PA', kind: 'boolean', source: 'native', ui: 'future' },
];

const mubertFilters = [
    { id: 'playlist_index', label: 'Channel', kind: 'playlist-index', source: 'native' },
    { id: 'duration', label: 'Duration', kind: 'duration', source: 'native', min: 15, max: 1500 },
    { id: 'intensity', label: 'Intensity', kind: 'select', source: 'native', values: ['low', 'medium', 'high'] },
    { id: 'mode', label: 'Mode', kind: 'select', source: 'native', values: ['track', 'jingle', 'loop', 'mix'] },
    { id: 'bpm', label: 'BPM', kind: 'number', source: 'native' },
    { id: 'format', label: 'Format', kind: 'select', source: 'native', values: ['mp3', 'wav'] },
];

const minimaxFilters = [
    { id: 'prompt', label: 'Prompt', kind: 'prompt', source: 'native' },
    { id: 'lyrics', label: 'Lyrics', kind: 'textarea', source: 'native', ui: 'future' },
    { id: 'is_instrumental', label: 'Instrumental', kind: 'boolean', source: 'native' },
    { id: 'output_format', label: 'Output', kind: 'select', source: 'native', values: ['hex', 'url'] },
    { id: 'audio_setting', label: 'Audio setting', kind: 'structured', source: 'native' },
    { id: 'preset', label: 'Presets Vibe_CUT', kind: 'preset', source: 'prompt-preset' },
];

const murekaFilters = [
    { id: 'prompt', label: 'Prompt', kind: 'prompt', source: 'native' },
    { id: 'lyrics', label: 'Lyrics', kind: 'textarea', source: 'native' },
    { id: 'instrumental', label: 'Instrumental', kind: 'boolean', source: 'native' },
    { id: 'task_query', label: 'Task query', kind: 'async-task', source: 'native' },
    { id: 'preset', label: 'Presets Vibe_CUT', kind: 'preset', source: 'prompt-preset' },
];

const replicateFilters = [
    { id: 'prompt', label: 'Prompt', kind: 'prompt', source: 'model-input' },
    { id: 'model', label: 'Model', kind: 'select', source: 'replicate-model' },
    { id: 'preset', label: 'Presets Vibe_CUT', kind: 'preset', source: 'prompt-preset' },
];

const promptPresetFilters = [
    { id: 'prompt', label: 'Prompt', kind: 'prompt', source: 'native-or-partner' },
    { id: 'duration', label: 'Duration', kind: 'duration', source: 'native-or-partner' },
    { id: 'preset', label: 'Presets Vibe_CUT', kind: 'preset', source: 'prompt-preset' },
];

export function getAiProviderDefinitions() {
    const minimaxConfigured = hasAnyEnv(['MINIMAX_API_KEY']);
    const murekaConfigured = hasAnyEnv(['MUREKA_API_KEY']);
    const replicateConfigured = hasAnyEnv(['REPLICATE_API_TOKEN']);
    const elevenConfigured = hasAnyEnv(['ELEVENLABS_API_KEY']);
    const stabilityConfigured = hasAnyEnv(['STABILITY_API_KEY']);
    const loudlyConfigured = hasAnyEnv(['LOUDLY_API_KEY']);
    const mubertConfigured = hasAllEnv(['MUBERT_CUSTOMER_ID', 'MUBERT_ACCESS_TOKEN']);
    const soundrawConfigured = hasAnyEnv(['SOUNDRAW_API_KEY']);
    const beatovenConfigured = hasAnyEnv(['BEATOVEN_API_KEY']);

    return [
        {
            id: 'minimax-music',
            label: 'MiniMax Music',
            mediaType: 'ai-music',
            type: 'generation-ai',
            status: minimaxConfigured ? 'api-active' : 'provider-missing-key',
            configured: minimaxConfigured,
            enabled: true,
            generationEnabled: true,
            keyEnv: ['MINIMAX_API_KEY'],
            officialDocsUrl: 'https://platform.minimax.io/docs/guides/music-generation',
            licenseUrl: 'https://platform.minimax.io/docs/guides/terms-of-service',
            importHostPolicy: 'server-generated-data-url-or-provider-url',
            note: 'Priorite prototype: API officielle /v1/music_generation, prompt + lyrics optionnels, instrumental, sortie hex ou URL expirant apres 24h.',
            controls: { prompt: true, duration: true, instrumental: true, variants: true, pagination: false },
            filters: minimaxFilters,
            presets: VIBECUT_PRESETS.map((preset) => ({ ...preset, mapping: 'prompt-preset' })),
            defaultDurationSeconds: 30,
            maxDurationSeconds: 360,
        },
        {
            id: 'mureka',
            label: 'Mureka API',
            mediaType: 'ai-music',
            type: 'generation-ai-async',
            status: murekaConfigured ? 'experimental' : 'provider-missing-key',
            configured: murekaConfigured,
            enabled: true,
            generationEnabled: true,
            keyEnv: ['MUREKA_API_KEY'],
            officialDocsUrl: 'https://platform.mureka.ai/docs/',
            licenseUrl: 'https://platform.mureka.ai/docs/',
            importHostPolicy: 'provider-url-or-user-file',
            note: 'API officielle orientee song/instrumental/lyrics/extension. Adapter automatique garde experimental tant que le schema de reponse compte/contrat n est pas valide.',
            controls: { prompt: true, duration: true, instrumental: true, variants: true, pagination: false },
            filters: murekaFilters,
            presets: VIBECUT_PRESETS.map((preset) => ({ ...preset, mapping: 'prompt-preset' })),
            defaultDurationSeconds: 30,
            maxDurationSeconds: 300,
        },
        {
            id: 'replicate-music',
            label: 'Replicate Music',
            mediaType: 'ai-music/model-hub',
            type: 'generation-ai-hub',
            status: replicateConfigured ? 'experimental' : 'provider-missing-key',
            configured: replicateConfigured,
            enabled: true,
            generationEnabled: true,
            keyEnv: ['REPLICATE_API_TOKEN'],
            officialDocsUrl: 'https://replicate.com/minimax/music-2.6',
            licenseUrl: 'https://replicate.com/minimax/music-2.6',
            importHostPolicy: 'replicate-delivery-url-or-user-file',
            note: 'Hub multi-modeles utile pour tester vite MiniMax/MusicGen/Riffusion. Generation automatique gardee experimental car chaque modele a son schema d input/licence.',
            controls: { prompt: true, duration: true, instrumental: true, variants: true, pagination: false },
            filters: replicateFilters,
            presets: VIBECUT_PRESETS.map((preset) => ({ ...preset, mapping: 'prompt-preset' })),
            defaultDurationSeconds: 30,
            maxDurationSeconds: 300,
        },
        {
            id: 'elevenlabs-music',
            label: 'ElevenLabs Music',
            mediaType: 'ai-music',
            type: 'generation-ai',
            status: elevenConfigured ? 'api-active' : 'provider-missing-key',
            configured: elevenConfigured,
            enabled: true,
            generationEnabled: true,
            keyEnv: ['ELEVENLABS_API_KEY'],
            officialDocsUrl: 'https://elevenlabs.io/docs/api-reference/music/compose-detailed',
            licenseUrl: 'https://elevenlabs.io/docs/eleven-creative/products/music',
            importHostPolicy: 'server-generated-data-url',
            note: 'API officielle /v1/music/detailed, prompt ou composition_plan, MP3/PCM selon plan, C2PA MP3 disponible.',
            controls: { prompt: true, duration: true, instrumental: true, variants: false, pagination: false },
            filters: elevenLabsFilters,
            presets: VIBECUT_PRESETS.map((preset) => ({ ...preset, mapping: 'prompt-preset' })),
            defaultDurationSeconds: 20,
            maxDurationSeconds: 600,
        },
        {
            id: 'stable-audio',
            label: 'Stable Audio',
            mediaType: 'ai-music/sfx',
            type: 'generation-ai',
            status: stabilityConfigured ? 'experimental' : 'provider-missing-key',
            configured: stabilityConfigured,
            enabled: true,
            generationEnabled: true,
            keyEnv: ['STABILITY_API_KEY'],
            officialDocsUrl: 'https://platform.stability.ai/docs/release-notes',
            licenseUrl: 'https://stability.ai/legal/terms-of-use',
            note: 'Stable Audio 3.0 API annoncee le 2026-05-20; endpoint public detaille non expose dans la page statique consultee. Provider garde experimental.',
            controls: { prompt: true, duration: true, instrumental: false, variants: false, pagination: false },
            filters: promptPresetFilters,
            presets: VIBECUT_PRESETS.map((preset) => ({ ...preset, mapping: 'prompt-preset' })),
            defaultDurationSeconds: 20,
            maxDurationSeconds: 360,
        },
        {
            id: 'loudly',
            label: 'Loudly API',
            mediaType: 'ai-music/catalog/stems',
            type: 'hybrid-ai-catalog',
            status: loudlyConfigured ? 'experimental' : 'provider-missing-key',
            configured: loudlyConfigured,
            enabled: true,
            generationEnabled: true,
            keyEnv: ['LOUDLY_API_KEY'],
            officialDocsUrl: 'https://www.loudly.com/music-api',
            licenseUrl: 'https://www.loudly.com/license-agreement',
            note: 'Page officielle annonce text-to-music, genre, tempo, energy, duration, catalogue, playlists et stems; docs endpoint publiques non accessibles sans portail.',
            controls: { prompt: true, duration: true, instrumental: false, variants: true, pagination: true },
            filters: [
                { id: 'genre', label: 'Genre', kind: 'select', source: 'native-public' },
                { id: 'tempo', label: 'Tempo', kind: 'select', source: 'native-public' },
                { id: 'energy', label: 'Energy', kind: 'select', source: 'native-public' },
                { id: 'duration', label: 'Duration', kind: 'duration', source: 'native-public' },
                { id: 'prompt', label: 'Text-to-music', kind: 'prompt', source: 'native-public' },
            ],
            presets: VIBECUT_PRESETS.map((preset) => ({ ...preset, mapping: 'prompt-preset' })),
            defaultDurationSeconds: 20,
            maxDurationSeconds: 180,
        },
        {
            id: 'mubert',
            label: 'Mubert API',
            mediaType: 'ai-music/streaming',
            type: 'generation-ai-streaming-catalog',
            status: mubertConfigured ? 'experimental' : 'provider-missing-key',
            configured: mubertConfigured,
            enabled: true,
            generationEnabled: true,
            keyEnv: ['MUBERT_CUSTOMER_ID', 'MUBERT_ACCESS_TOKEN'],
            officialDocsUrl: 'https://mubert.com/api/docs',
            licenseUrl: 'https://mubert.com/api',
            note: 'API officielle v3: public/tracks, public/playlists, streaming, mp3/wav, intensity, mode, BPM/key et sublicensing selon contrat.',
            controls: { prompt: true, duration: true, instrumental: false, variants: true, pagination: true },
            filters: mubertFilters,
            presets: [
                { id: 'ambient-lounge', label: 'ambient / lounge', playlistIndex: '3.0.0', prompt: 'ambient lounge bed', mapping: 'mapped' },
                { id: 'tech-futuristic', label: 'tech / futuristic', playlistIndex: '1.0.0', prompt: 'futuristic technology music', mapping: 'mapped' },
                { id: 'house', label: 'house', playlistIndex: '1.0.0', prompt: 'house groove', mapping: 'mapped' },
                ...VIBECUT_PRESETS.filter((preset) => !['ambient-lounge', 'tech-futuristic', 'house'].includes(preset.id)).map((preset) => ({ ...preset, mapping: 'prompt-preset' })),
            ],
            defaultDurationSeconds: 20,
            maxDurationSeconds: 1500,
        },
        {
            id: 'soundraw',
            label: 'SOUNDRAW API',
            mediaType: 'ai-music',
            type: 'generation-ai',
            status: soundrawConfigured ? 'experimental' : 'provider-missing-key',
            configured: soundrawConfigured,
            enabled: true,
            generationEnabled: true,
            keyEnv: ['SOUNDRAW_API_KEY'],
            officialDocsUrl: 'https://soundraw.io/api',
            licenseUrl: 'https://soundraw.io/api',
            note: 'Page officielle expose Genre, Mood, Theme et licence commerciale; endpoints techniques publics non inclus dans la page.',
            controls: { prompt: false, duration: true, instrumental: false, variants: true, pagination: true },
            filters: [
                { id: 'genre', label: 'Genre', kind: 'select', source: 'native-public' },
                { id: 'mood', label: 'Mood', kind: 'select', source: 'native-public' },
                { id: 'theme', label: 'Theme', kind: 'select', source: 'native-public' },
            ],
            presets: VIBECUT_PRESETS.map((preset) => ({ ...preset, mapping: 'prompt-preset' })),
            defaultDurationSeconds: 20,
            maxDurationSeconds: 180,
        },
        {
            id: 'beatoven',
            label: 'Beatoven.ai',
            mediaType: 'ai-music/sfx',
            type: 'generation-ai-sfx',
            status: beatovenConfigured ? 'experimental' : 'provider-missing-key',
            configured: beatovenConfigured,
            enabled: true,
            generationEnabled: true,
            keyEnv: ['BEATOVEN_API_KEY'],
            officialDocsUrl: 'https://www.beatoven.ai/api',
            licenseUrl: 'https://www.beatoven.ai/licensing',
            note: 'maestro Music Generation API et SFX API annonces; dashboard requis pour details endpoint. Garde experimental avant test contractuel.',
            controls: { prompt: true, duration: true, instrumental: true, variants: false, pagination: false },
            filters: promptPresetFilters,
            presets: VIBECUT_PRESETS.map((preset) => ({ ...preset, mapping: 'prompt-preset' })),
            defaultDurationSeconds: 20,
            maxDurationSeconds: 180,
        },
    ];
}

export function getAiProviderDefinition(providerId) {
    return getAiProviderDefinitions().find((provider) => provider.id === providerId) || null;
}
