"use strict";

const PROVIDER_REGISTRY = Object.freeze({
  mock: Object.freeze({
    id: "mock",
    region: "local",
    access: "internal-test",
    modalities: ["text"],
    apiStyle: "internal",
    dataPolicy: "no-external-call",
    pricingUrl: "",
    reliabilityTier: "test",
    legalRisk: "low",
    status: "candidate",
    productionAllowed: false,
    notes: "Provider interne pour tester credits, idempotence et dashboard sans cout API.",
  }),
  openai: Object.freeze({
    id: "openai",
    region: "US/EU",
    access: "direct-api",
    modalities: ["text", "vision", "image", "audio", "video"],
    apiStyle: "openai",
    dataPolicy: "verify-official",
    pricingUrl: "https://openai.com/api/pricing/",
    reliabilityTier: "candidate",
    legalRisk: "low",
    status: "candidate",
    productionAllowed: false,
    notes: "Activer seulement apres benchmark, budget caps, retention/data controls et validation des modeles exacts.",
  }),
  anthropic: Object.freeze({
    id: "anthropic",
    region: "US/EU",
    access: "direct-api",
    modalities: ["text", "vision"],
    apiStyle: "anthropic",
    dataPolicy: "verify-official",
    pricingUrl: "https://platform.claude.com/docs/en/about-claude/pricing",
    reliabilityTier: "candidate",
    legalRisk: "low",
    status: "candidate",
    productionAllowed: false,
    notes: "Candidate premium texte/vision apres verification DPA, retention, quotas et couts.",
  }),
  mistral: Object.freeze({
    id: "mistral",
    region: "EU",
    access: "direct-api",
    modalities: ["text"],
    apiStyle: "openai-compatible",
    dataPolicy: "verify-official",
    pricingUrl: "https://mistral.ai/",
    reliabilityTier: "candidate",
    legalRisk: "low",
    status: "candidate",
    productionAllowed: false,
    notes: "Candidate EU pour texte, a benchmarker et documenter avant exposition utilisateur.",
  }),
  gemini: Object.freeze({
    id: "gemini",
    region: "global",
    access: "direct-api",
    modalities: ["text", "vision", "image", "audio", "video"],
    apiStyle: "google",
    dataPolicy: "verify-official",
    pricingUrl: "https://ai.google.dev/gemini-api/docs/pricing",
    reliabilityTier: "candidate",
    legalRisk: "low",
    status: "candidate",
    productionAllowed: false,
    notes: "Candidate low-cost/standard selon benchmark et conditions data Google.",
  }),
  groq: Object.freeze({
    id: "groq",
    region: "US",
    access: "direct-api",
    modalities: ["text", "audio"],
    apiStyle: "openai-compatible",
    dataPolicy: "verify-official",
    pricingUrl: "https://groq.com/pricing",
    reliabilityTier: "candidate",
    legalRisk: "medium",
    status: "candidate",
    productionAllowed: false,
    notes: "Candidate faible latence texte/transcription, a verifier pour couts, quotas et retention.",
  }),
  deepseek: Object.freeze({
    id: "deepseek",
    region: "CN",
    access: "direct-api",
    modalities: ["text", "reasoning", "coding"],
    apiStyle: "openai-compatible",
    dataPolicy: "verify-official",
    pricingUrl: "https://api-docs.deepseek.com/",
    reliabilityTier: "candidate",
    legalRisk: "medium",
    status: "candidate",
    productionAllowed: false,
    notes: "Activer seulement apres verification DPA, logs, retention, paiement, quotas et conformite.",
  }),
  qwen: Object.freeze({
    id: "qwen",
    region: "CN",
    access: "direct-api-or-hosted",
    modalities: ["text", "vision", "image"],
    apiStyle: "model-studio",
    dataPolicy: "verify-official",
    pricingUrl: "https://www.alibabacloud.com/help/en/model-studio/",
    reliabilityTier: "candidate",
    legalRisk: "medium",
    status: "candidate",
    productionAllowed: false,
    notes: "Candidate non-US via Alibaba Model Studio ou hebergement verifie.",
  }),
  kimi: Object.freeze({
    id: "kimi",
    region: "CN",
    access: "direct-api",
    modalities: ["text"],
    apiStyle: "openai-compatible",
    dataPolicy: "verify-official",
    pricingUrl: "https://www.kimi.com/help/kimi-api/api-pricing",
    reliabilityTier: "candidate",
    legalRisk: "medium",
    status: "candidate",
    productionAllowed: false,
    notes: "Candidate Moonshot/Kimi a verifier pour retention, facturation et disponibilite pays.",
  }),
  zhipu: Object.freeze({
    id: "zhipu",
    region: "CN",
    access: "direct-api",
    modalities: ["text", "vision", "image"],
    apiStyle: "glm",
    dataPolicy: "verify-official",
    pricingUrl: "https://open.bigmodel.cn/",
    reliabilityTier: "candidate",
    legalRisk: "medium",
    status: "candidate",
    productionAllowed: false,
    notes: "Candidate GLM a verifier juridiquement avant tout usage utilisateur.",
  }),
  minimax: Object.freeze({
    id: "minimax",
    region: "CN/global",
    access: "direct-api",
    modalities: ["text", "audio", "video"],
    apiStyle: "minimax",
    dataPolicy: "verify-official",
    pricingUrl: "https://platform.minimax.io/docs/pricing/overview",
    reliabilityTier: "candidate",
    legalRisk: "medium",
    status: "candidate",
    productionAllowed: false,
    notes: "Candidate video/audio selon API officielle, droits commerciaux et disponibilite locale.",
  }),
  bytedance_seed: Object.freeze({
    id: "bytedance_seed",
    region: "CN/global",
    access: "enterprise-official-only",
    modalities: ["text", "image", "video"],
    apiStyle: "byteplus-or-volcengine",
    dataPolicy: "verify-contract",
    pricingUrl: "",
    reliabilityTier: "candidate",
    legalRisk: "high",
    status: "candidate",
    productionAllowed: false,
    notes: "Ne pas utiliser via proxy non officiel; verifier contrat BytePlus/Volcengine, KYC, regions et deepfake policy.",
  }),
  fal: Object.freeze({
    id: "fal",
    region: "US/global",
    access: "aggregator",
    modalities: ["image", "video", "audio"],
    apiStyle: "fal",
    dataPolicy: "verify-official",
    pricingUrl: "https://docs.fal.ai/documentation/model-apis/pricing",
    reliabilityTier: "candidate",
    legalRisk: "medium",
    status: "candidate",
    productionAllowed: false,
    notes: "Aggregator utile pour media open-weight; verrouiller modele/provider/cout max avant production.",
  }),
  replicate: Object.freeze({
    id: "replicate",
    region: "US/global",
    access: "aggregator",
    modalities: ["image", "video", "audio", "text"],
    apiStyle: "replicate",
    dataPolicy: "verify-official",
    pricingUrl: "https://replicate.com/pricing",
    reliabilityTier: "candidate",
    legalRisk: "medium",
    status: "candidate",
    productionAllowed: false,
    notes: "Verifier licence du modele exact, retention et cout avant usage.",
  }),
  runware: Object.freeze({
    id: "runware",
    region: "global",
    access: "aggregator",
    modalities: ["image", "video"],
    apiStyle: "runware",
    dataPolicy: "verify-official",
    pricingUrl: "https://runware.ai/pricing/",
    reliabilityTier: "candidate",
    legalRisk: "medium",
    status: "candidate",
    productionAllowed: false,
    notes: "Candidate draft image/video apres benchmark cout/qualite et moderation.",
  }),
  openrouter: Object.freeze({
    id: "openrouter",
    region: "global",
    access: "router",
    modalities: ["text", "vision"],
    apiStyle: "openai-compatible",
    dataPolicy: "verify-official-and-provider-lock",
    pricingUrl: "https://openrouter.ai/pricing",
    reliabilityTier: "candidate",
    legalRisk: "medium",
    status: "candidate",
    productionAllowed: false,
    notes: "Utilisable seulement avec provider/model verrouille et cout max; pas de routage opaque.",
  }),
  together: Object.freeze({
    id: "together",
    region: "US/global",
    access: "aggregator",
    modalities: ["text", "image"],
    apiStyle: "openai-compatible",
    dataPolicy: "verify-official",
    pricingUrl: "https://www.together.ai/pricing",
    reliabilityTier: "candidate",
    legalRisk: "medium",
    status: "candidate",
    productionAllowed: false,
    notes: "Candidate open-weight heberge apres verification modele, licence, retention et couts.",
  }),
  fireworks: Object.freeze({
    id: "fireworks",
    region: "US/global",
    access: "aggregator",
    modalities: ["text", "image"],
    apiStyle: "openai-compatible",
    dataPolicy: "verify-official",
    pricingUrl: "https://fireworks.ai/pricing",
    reliabilityTier: "candidate",
    legalRisk: "medium",
    status: "candidate",
    productionAllowed: false,
    notes: "Candidate open-weight heberge; verifier provider lock, quotas et modeles.",
  }),
  huggingface: Object.freeze({
    id: "huggingface",
    region: "global",
    access: "inference-provider-or-model-hub",
    modalities: ["text", "image", "audio", "video"],
    apiStyle: "hf",
    dataPolicy: "verify-per-provider",
    pricingUrl: "https://huggingface.co/docs/api-inference/en/pricing",
    reliabilityTier: "candidate",
    legalRisk: "medium",
    status: "candidate",
    productionAllowed: false,
    notes: "Verifier provider effectif, modele, licence commerciale et safety review.",
  }),
  ideogram: Object.freeze({
    id: "ideogram",
    region: "global",
    access: "direct-api",
    modalities: ["image"],
    apiStyle: "ideogram",
    dataPolicy: "verify-official",
    pricingUrl: "https://ideogram.ai/features/api-pricing",
    reliabilityTier: "candidate",
    legalRisk: "medium",
    status: "candidate",
    productionAllowed: false,
    notes: "Candidate image typo/logo apres verification droits commerciaux et moderation.",
  }),
  leonardo: Object.freeze({
    id: "leonardo",
    region: "global",
    access: "direct-api",
    modalities: ["image"],
    apiStyle: "leonardo",
    dataPolicy: "verify-official",
    pricingUrl: "https://leonardo.ai/pricing/",
    reliabilityTier: "candidate",
    legalRisk: "medium",
    status: "candidate",
    productionAllowed: false,
    notes: "Candidate workflow createur; verifier API/pricing, licences et safety.",
  }),
  mubert: Object.freeze({
    id: "mubert",
    region: "global",
    access: "direct-api",
    modalities: ["music", "audio"],
    apiStyle: "mubert",
    dataPolicy: "verify-official",
    pricingUrl: "https://mubert.com/api",
    reliabilityTier: "candidate",
    legalRisk: "medium",
    status: "candidate",
    productionAllowed: false,
    notes: "Candidate musique IA avec manifest droits obligatoire avant export/publication.",
  }),
  midjourney: Object.freeze({
    id: "midjourney",
    region: "US",
    access: "manual-reference-only",
    modalities: ["image"],
    apiStyle: "none",
    dataPolicy: "not-applicable",
    pricingUrl: "",
    reliabilityTier: "blocked",
    legalRisk: "high",
    status: "blocked",
    productionAllowed: false,
    notes: "Bloque tant qu'il n'existe pas d'API officielle publique et de droits d'automatisation clairs.",
  }),
  civitai: Object.freeze({
    id: "civitai",
    region: "marketplace",
    access: "model-source",
    modalities: ["image"],
    apiStyle: "marketplace",
    dataPolicy: "per-model-review",
    pricingUrl: "",
    reliabilityTier: "candidate",
    legalRisk: "high",
    status: "candidate",
    productionAllowed: false,
    notes: "Jamais trusted globalement; review par modele avec licence, hash, createur, restrictions et safety.",
  }),
});

function providerList() {
  return Object.values(PROVIDER_REGISTRY);
}

function getProvider(providerId) {
  return PROVIDER_REGISTRY[String(providerId || "")] || null;
}

function publicProviderRegistry() {
  return providerList().map((provider) => ({
    id: provider.id,
    access: provider.access,
    modalities: provider.modalities,
    status: provider.status,
    productionAllowed: provider.productionAllowed,
    legalRisk: provider.legalRisk,
    pricingUrl: provider.pricingUrl,
  }));
}

function assertProviderUsable(provider, policy, options = {}) {
  if (!provider) throw new Error("provider_not_registered");
  if (provider.status === "blocked") throw new Error("provider_blocked");
  if (!provider.modalities.includes(policy.modality)) throw new Error("provider_modality_unsupported");
  if (options.productionRuntime === true && (!provider.productionAllowed || policy.productionAllowed !== true)) {
    throw new Error("provider_not_allowed_in_production");
  }
}

module.exports = {
  PROVIDER_REGISTRY,
  providerList,
  getProvider,
  publicProviderRegistry,
  assertProviderUsable,
};
