const COMMON_OPTIONS = Object.freeze({
  quality: [
    { id: 'draft', label: 'Draft', detail: 'Texte mock, 1 credit' },
    { id: 'standard', label: 'Standard', detail: 'Policy serveur requise' },
    { id: 'premium', label: 'Premium', detail: 'Provider bloque en beta' },
  ],
});

const AI_ACTIONS_BY_VIEW = Object.freeze({
  studio: [
    {
      id: 'studio-polish',
      label: 'Ameliorer cette image',
      agent: 'Style Director',
      feature: 'image.edit.social_polish',
      type: 'image',
      credits: 80,
      duration: '45-90s',
      output: 'Variante image',
      intent: 'add_variant',
      requiresImage: true,
      productionBlocked: true,
      examplePrompt: 'Rends cette image plus nette, premium, lumineuse, sans changer le sujet.',
    },
    {
      id: 'studio-moods',
      label: 'Creer 3 moods social',
      agent: 'Style Director',
      feature: 'image.variation.style_set',
      type: 'image',
      credits: 120,
      duration: '60-120s',
      output: 'Presets non destructifs',
      intent: 'apply_to_canvas',
      requiresImage: true,
      productionBlocked: true,
      examplePrompt: 'Propose trois moods reels: premium, neon, editorial.',
    },
    {
      id: 'studio-caption',
      label: 'Generer caption + hashtags',
      agent: 'Style Director',
      feature: 'text.caption.draft',
      type: 'text',
      credits: 1,
      duration: '5-10s',
      output: 'Caption publication',
      intent: 'send_to_publication',
      runnable: true,
      examplePrompt: 'Caption Instagram courte pour ce rendu, ton premium, CTA reservation.',
    },
    {
      id: 'studio-prompt-rewrite',
      label: 'Reecrire mon prompt image',
      agent: 'Style Director',
      feature: 'text.prompt_rewrite.draft',
      type: 'text',
      credits: 1,
      duration: '5-10s',
      output: 'Prompt exploitable',
      intent: 'copy_prompt',
      runnable: true,
      examplePrompt: 'Une affiche cyber premium pour lancer une offre social media.',
    },
  ],
  fusion: [
    {
      id: 'fusion-background',
      label: 'Generer un fond de campagne',
      agent: 'Composition Lab',
      feature: 'image.generate.social_background',
      type: 'image',
      credits: 70,
      duration: '40-80s',
      output: 'Fond stocke',
      intent: 'apply_background',
      productionBlocked: true,
      examplePrompt: 'Fond neon premium pour une campagne de lancement, lisible derriere du texte blanc.',
    },
    {
      id: 'fusion-palette',
      label: 'Extraire une palette',
      agent: 'Composition Lab',
      feature: 'vision.palette.extract',
      type: 'layout_patch',
      credits: 8,
      duration: '10-20s',
      output: 'Roles couleurs',
      intent: 'apply_palette',
      requiresImage: true,
      productionBlocked: true,
      examplePrompt: 'Extrais une palette avec roles background, signal, CTA et texte.',
    },
    {
      id: 'fusion-recipe',
      label: 'Composer une affiche',
      agent: 'Composition Lab',
      feature: 'text.composition.recipe',
      type: 'text',
      credits: 1,
      duration: '5-10s',
      output: 'Recette composition',
      intent: 'apply_to_canvas',
      runnable: true,
      featureOverride: 'text.prompt_rewrite.draft',
      examplePrompt: 'Brief: concert electro vendredi soir, format story, energie neon.',
    },
    {
      id: 'fusion-texture',
      label: 'Generer overlay texture',
      agent: 'Composition Lab',
      feature: 'image.generate.overlay_texture',
      type: 'image',
      credits: 35,
      duration: '30-60s',
      output: 'Texture importable',
      intent: 'add_texture',
      productionBlocked: true,
      examplePrompt: 'Texture scanline subtile, grain propre, aucun texte.',
    },
  ],
  layout: [
    {
      id: 'layout-brief',
      label: 'Generer un layout depuis brief',
      agent: 'Social Layout Builder',
      feature: 'text.layout.copy_social',
      type: 'layout_patch',
      credits: 3,
      duration: '10-20s',
      output: 'Patch layout',
      intent: 'apply_layout_patch',
      runnable: true,
      featureOverride: 'text.prompt_rewrite.draft',
      examplePrompt: 'Je vends une offre coaching fitness, ton premium, CTA reservation.',
    },
    {
      id: 'layout-carousel',
      label: 'Adapter en carrousel',
      agent: 'Social Layout Builder',
      feature: 'text.layout.copy_social',
      type: 'layout_patch',
      credits: 3,
      duration: '10-20s',
      output: 'Structure 2-3 slides',
      intent: 'apply_layout_patch',
      runnable: true,
      featureOverride: 'text.prompt_rewrite.draft',
      examplePrompt: 'Transforme ce visuel en carrousel 3 slides: probleme, preuve, CTA.',
    },
    {
      id: 'layout-copy',
      label: 'Ecrire les textes du visuel',
      agent: 'Social Layout Builder',
      feature: 'text.layout.copy_social',
      type: 'text',
      credits: 1,
      duration: '5-10s',
      output: 'Titre, sous-titre, CTA',
      intent: 'apply_to_canvas',
      runnable: true,
      featureOverride: 'text.caption.draft',
      examplePrompt: 'Titre court, sous-titre clair, CTA pour une offre social media premium.',
    },
    {
      id: 'layout-readability',
      label: 'Verifier lisibilite',
      agent: 'Social Layout Builder',
      feature: 'text.layout.accessibility_check',
      type: 'text',
      credits: 1,
      duration: '5-10s',
      output: 'Rapport lisibilite',
      intent: 'apply_to_canvas',
      runnable: true,
      featureOverride: 'text.prompt_rewrite.draft',
      examplePrompt: 'Verifie contraste, safe areas, taille des mots et hierarchie.',
    },
  ],
  'vision-pro': [
    {
      id: 'vision-polish',
      label: 'Polish premium',
      agent: 'Polish Pro',
      feature: 'image.edit.vision_polish',
      type: 'image',
      credits: 120,
      duration: '60-120s',
      output: 'Image retouchee',
      intent: 'add_variant',
      requiresImage: true,
      productionBlocked: true,
      warning: 'Modifie les pixels, pas juste des sliders.',
      examplePrompt: 'Retouche premium: peau naturelle, detail propre, lumiere plus haut de gamme.',
    },
    {
      id: 'vision-rescue',
      label: 'Sauver une photo smartphone',
      agent: 'Polish Pro',
      feature: 'image.edit.smartphone_rescue',
      type: 'image',
      credits: 95,
      duration: '45-90s',
      output: 'Variante restauree',
      intent: 'add_variant',
      requiresImage: true,
      productionBlocked: true,
      examplePrompt: 'Debruite, dehaze, recupere les basses lumieres et garde les tons peau naturels.',
    },
    {
      id: 'vision-upscale',
      label: 'Upscale social',
      agent: 'Polish Pro',
      feature: 'image.upscale.social',
      type: 'image',
      credits: 90,
      duration: '45-90s',
      output: '1080/1440/2160',
      intent: 'add_variant',
      requiresImage: true,
      productionBlocked: true,
      examplePrompt: 'Upscale propre pour format social, sans artefacts ni visage modifie.',
    },
    {
      id: 'vision-compare',
      label: 'Comparer gratuit vs IA',
      agent: 'Polish Pro',
      feature: 'text.prompt_rewrite.draft',
      type: 'text',
      credits: 1,
      duration: '5-10s',
      output: 'Rapport avant/apres',
      intent: 'apply_to_canvas',
      runnable: true,
      examplePrompt: 'Explique ce que le polish IA apporterait par rapport aux filtres locaux.',
    },
  ],
  video: [
    {
      id: 'video-generate',
      label: 'Generer avec IA',
      agent: 'Clip Director',
      feature: 'video.generate.text_to_video',
      type: 'video',
      credits: 650,
      duration: '2-6min',
      output: 'Clip timeline',
      intent: 'add_to_timeline',
      productionBlocked: true,
      videoDurations: [4, 6, 8, 16, 20],
      examplePrompt: 'Video verticale 8s, produit premium, camera lente, lumiere neon.',
    },
    {
      id: 'video-animate-image',
      label: 'Animer cette image',
      agent: 'Clip Director',
      feature: 'video.generate.image_to_video',
      type: 'video',
      credits: 520,
      duration: '2-5min',
      output: 'Image-to-video',
      intent: 'add_to_timeline',
      productionBlocked: true,
      requiresImage: true,
      videoDurations: [4, 6, 8],
      examplePrompt: 'Anime l image avec un mouvement camera doux et profondeur subtile.',
    },
    {
      id: 'video-broll',
      label: 'Creer un B-roll',
      agent: 'Clip Director',
      feature: 'video.generate.broll',
      type: 'video',
      credits: 480,
      duration: '2-5min',
      output: 'B-roll timeline',
      intent: 'add_to_timeline',
      productionBlocked: true,
      videoDurations: [4, 6, 8, 16],
      examplePrompt: 'B-roll 6s pour une marque fitness premium, details produit et motion clean.',
    },
    {
      id: 'video-storyboard',
      label: 'Storyboard reel 30s',
      agent: 'Clip Director',
      feature: 'video.storyboard.social_reel',
      type: 'text',
      credits: 2,
      duration: '10-20s',
      output: 'Plan 3-5 shots',
      intent: 'add_to_timeline',
      runnable: true,
      featureOverride: 'text.prompt_rewrite.draft',
      examplePrompt: 'Storyboard reel 30s en 4 shots courts pour une offre coaching.',
    },
  ],
  library: [
    {
      id: 'library-stickers',
      label: 'Generer pack stickers',
      agent: 'Asset Scout',
      feature: 'image.generate.asset_pack',
      type: 'image',
      credits: 90,
      duration: '60-120s',
      output: '4 PNG/WebP',
      intent: 'add_to_library',
      productionBlocked: true,
      examplePrompt: 'Pack de stickers neon coherents pour une campagne social media.',
    },
    {
      id: 'library-texture',
      label: 'Generer texture',
      agent: 'Asset Scout',
      feature: 'image.generate.texture_pack',
      type: 'image',
      credits: 50,
      duration: '30-60s',
      output: 'Textures library',
      intent: 'add_texture',
      productionBlocked: true,
      examplePrompt: 'Texture hologramme subtile, grain fin, fond transparent si possible.',
    },
    {
      id: 'library-classify',
      label: 'Classer mes imports',
      agent: 'Asset Scout',
      feature: 'vision.asset.classify',
      type: 'text',
      credits: 1,
      duration: '5-10s',
      output: 'Tags assets',
      intent: 'add_to_library',
      runnable: true,
      featureOverride: 'text.prompt_rewrite.draft',
      examplePrompt: 'Classe mes assets par usage: fond, texture, sujet, sticker, social safe.',
    },
  ],
});

export function getStudioAiActions(view) {
  return AI_ACTIONS_BY_VIEW[view] || AI_ACTIONS_BY_VIEW.studio;
}

export function getStudioAiAgentName(view) {
  const firstAction = getStudioAiActions(view)[0];
  return firstAction?.agent || 'Agent IA';
}

export function getStudioAiOptions() {
  return COMMON_OPTIONS;
}

